services:

  drink_safely:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drink_safely
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ./backend:/src/app
    environment:
      DB_USER: "user"
      DB_PASSWORD: "password"
      DB_NAME: "mydatabase"

  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
       - database_data:/var/lib/postgresql/data

volumes:
  database_data:
