services:

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ./backend:/src/app
    environment:
      DB_USER: "user"
      DB_PASSWORD: "password"
      DB_NAME: "mydatabase"

  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
       - database_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://127.0.0.1:8000
    volumes:
      - ./frontend:/app

volumes:
  database_data:
