POPULATE_DATA = {
    "Fun": {
        "cards": [
            "Act out a scene from your a movie, except Titanic. If someone guesses correctly, you can distribute 5 sips. If no one guesses, you drink 4 times.",
            "Impersonate another player for the next round. Each time you break character, take a sip.",
            "Tell a joke. If no one laughs, you drink 5. If someone laughs, they take 5 sips.",
            "Speak in an accent chosen by the group for the next 3 rounds. Every time you forget, drink.",
            "Show the last photo on your phone or take 6 sips.",
            "Try to lick your elbow. If you can't, take 6 sips.",
            "Balance an item on your head for 10 seconds. If it falls, you drink twice.",
            "Swap shoes with the person across from you for 1 round. No exceptions.",
            "Recite the alphabet backwards, the group can decide the letter you start on. Take a sip for each mistake.",
            "Draw a portrait of another player in this game with your eyes closed. You have one minute. If the group can recognize who it is, distribute 10 sips. If they can't, drink 5.",
            "Speak in rhymes for the next 2 rounds. Drink 2 sips each time you fail.",
            "Act out an emoji without speaking. If no one guesses in 30 seconds, drink 3 sips.",
            "Perform a dramatic reading of the last text message you sent. If you refuse, drink 4 sips.",
            "Try to name 10 types of pasta in 20 seconds. Drink for each one you miss.",
        ]
    },
    "Virus": {
        "cards": [
            "Drink 3 sips if you speak out of turn. Duration: 1 Round.",
            "Drink 4 sips if you check your phone without permission. If you want/need to check it you must receive permission from the group. Duration: For the rest of the Game.",
            "Take 3 sips if you interrupt someone. Duration: 2 Rounds.",
            "Drink 2 sips if you curse. Duration: 2 Rounds.",
            "Take 3 sips if you make eye contact with anoyone. Duration: 2 Rounds.",
            "You are the Meduse. If you can get someone to look at you, they must drink. Duration: 2 Rounds.",
            "Drink 3 sips everytime you say 'tipo'. Duration: 2 Rounds.",
            "Drink 2 in your turn. Duration: 2 Rounds.",
            "Drink 2 sips if you touch any part of your body. If you get itchy ask some help. Duration: 2 Round.",
        ]
    },
    "Lucky Breaks": {
        "cards": [
            "Choose someone to take 2 sips.",
            "Give out 3 sips to any player(s) of your choice.",
            "Make a rule for the next 2 round.",
            "Make any player drink 5 sips.",
            "Double sips for everyone except you for the next 2 Rounds.",
            "Choose a player to be your drinking buddy for the next 3 Rounds.",
        ]
    },
    "Mini Games": {
        "cards": [
            "Chose a player to play Rock, Paper, Scissors. Loser drinks 3.",
            "Thumb war with the person to your right. Loser drinks.",
            "Pictionary: draw something and have others guess. The one who guesses right gives out 2 sips.",
            "Two Truths and a Lie: If someone guesses your lie, you drink 3 sips. If no one guesses, you get to distribute 6 sips.",
            "Quick game of categories (e.g., types of fruit). The first person to hesitate or repeat drinks.",
            "Memory game: Everyone says a word in turn, repeating the previous words and adding a new one. The first person to mess up drinks.",
            "Quick round of spelling bee: Whoever misspells drinks 3.",
            "Coin flip challenge: Predict 3 coin flips in a row or drink 5.",
            "Name that tune: Hum a song, first to guess correctly gives out 3 sips.",
            "20 Questions: If the group can't guess your object, distribute 10 sips.",
            "Rhyme Time: Say a word, next person must rhyme. Fail and drink 3.",
            "Alphabet Game: Name items in a category in alphabetical order. Mistake = drink 2.",
            "Count to 20: Each person says a number, but multiples of 3 are skipped. Mess up, drink 3.",
            "Who Am I?: Guess the person your thinking in 10 questions. If the group can't, distribute 8 sips, else drink 3.",
            "Blind Drawing: Agree on one item/animal/whatever. Everyone with their eyes closed draw it in 1 minute. Worst drawing drinks 4.",
            "Spell It Out: Choose a word adn spell it with your body. Team can't guess, drink 2.",
            "Arm wrestle the person to your left. Loser drinks 2.",
            "Staring contest with the person across from you. Loser drinks 2.",
            "Balance on one leg for 30 seconds. If you fail, give out 5 sips, your too drunk.",
            "Try to touch your nose with your tongue. If you fail, drink.",
            "Sing a part of a song chosen by the group. If you don't know it, drink 3.",
            "Build a card tower with 4 stories with a partner in 1 minute. If it falls, both drink 3 sips.",
        ]
    },
    "Trivia": {
        "settings": {"for_all_players": True},
        "cards": [
            "What is the capital of Australia? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "Who painted the Mona Lisa? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What year did World War II end? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What is the largest planet in our solar system? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "Who wrote the play 'Romeo and Juliet'? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What is the chemical symbol for gold? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "Who was the first person to step on the moon? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What is the longest river in the world? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "In which year did the Titanic sink? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What is the smallest country in the world? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What is the hardest natural substance on Earth? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "Which planet is known as the Red Planet? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "Who painted 'The Starry Night'? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What is the largest ocean on Earth? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What is the capital of Canada? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "Which element has the chemical symbol 'O'? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What is the fastest land animal? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "In which country would you find the Eiffel Tower? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "Who discovered penicillin? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What is the largest desert in the world? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "Who was the first woman to win a Nobel Prize? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What is the currency of Japan? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "Who painted the Sistine Chapel ceiling? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What is the main ingredient in guacamole? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "Which country is home to the kangaroo? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What is the boiling point of water in Celsius? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What does WWW mean? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
            "What is the capital of Brazil? If you are the only one who guesses right, you can distribute 10 sips. If not, whoever got it wrong drinks twice.",
        ],
    },
    "Look Around You": {
        "cards": [
            "Close your eyes. What is the color of the shirt of the player to your right? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "Without looking, how many people are wearing glasses? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "What is the color of the nearest wall to you? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "How many doors are in the room you are in? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "What type of shoes is the person across from you wearing? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "How many windows are in the room? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "Without looking, what time is it? (closest guess wins) If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "What is the color of the player's phone to your left? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "How many people are wearing a watch? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "Without looking, what is the brand of the TV (or monitor) in the room? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "What color are the socks of the player to your left? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "How many light fixtures are in the room? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "Without looking, how many cushions are on the nearest couch or chair? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "What color is the player's hair to your right? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "How many people are wearing jewelry? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "What is the color of the floor/carpet in the room? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "Without looking, what is the nearest object to your left? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "What is the pattern on the nearest cushion or pillow? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "How many players are wearing something red? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "Without looking, how many chairs are in the room? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "What color are the eyes of the person sitting opposite you? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "What is the color of the largest object in the room? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "How many people are wearing something blue? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "What is the brand of the nearest electronic device to you? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
            "Without looking, how many people are wearing something on their wrists? If you get it wrong, drink 2. If you get it right, tell someone to drink 1.",
        ]
    },
    "Would You Rather": {
        "settings": {"for_all_players": True},
        "cards": [
            "Would you rather lose all your money and valuables or all the pictures you have ever taken? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather accidentally send a risqué message to your boss or to your parents? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather always be 10 minutes late or always be 20 minutes early? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather get caught having sex in public or accidentally broadcast it on social media? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather bite your tongue every time you eat or get a paper cut every time you touch paper? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather always have an annoying song stuck in your head or always have an itch that you can't reach? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather be famous when you are alive and forgotten when you die or unknown when you are alive but famous after you die? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have a constant itch or constant hiccups? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather be alone for the rest of your life or always be surrounded by annoying people? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have an easy job working for someone else or work for yourself but work incredibly hard? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather accidentally like an old photo of your ex on social media or send a sext to the wrong person? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather be locked in a room that is constantly dark for a week or a room that is constantly bright for a week? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have a visible tattoo of the last thing you ate or a visible tattoo of the last person you texted? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather be the first person to explore a planet or be the inventor of a drug that cures a deadly disease? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather never have sex again or never eat your favorite food again? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather never be able to wash your hair or never be able to cut your nails? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather be completely invisible for one day or be able to fly for one day? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have free Wi-Fi wherever you go or have free coffee where/whenever you want? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have to kiss everyone you meet or never kiss your significant other again? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather be able to teleport anywhere or be able to read minds? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have a one-night stand with someone really attractive who is terrible in bed or someone unattractive who is amazing in bed? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have a giant zit on your forehead for a year or have to wear braces for two years? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather lick a public bathroom floor or a stranger's foot? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have your browser history made public or the last 20 pictures in your camera roll? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather eat a bowl of spaghetti noodles without sauce or a bowl of spaghetti sauce without noodles? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather be poor but help people or become incredibly rich by hurting people? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather spend a week in the wilderness or one night in a haunted house? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather always feel like you have to sneeze or always feel like you have to pee? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather die in 20 years with no regrets or die in 50 years with many regrets? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather walk in on your parents having sex or have them walk in on you? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather live in the wilderness far from civilization or live on the streets of a city as a homeless person? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather always have to hop on one foot or always have to squat? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have a horrible job but be able to retire comfortably in 10 years or have your dream job but have to work until the day you die? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather be feared by all or loved by all? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have to say everything that comes to your mind or never speak again? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have a head the size of a tennis ball or the size of a watermelon? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have a horrible short-term memory or a horrible long-term memory? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather find out your partner cheated on you with your best friend or your worst enemy? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather live your entire life in a virtual reality where all your wishes are granted or in the real world? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather drink a cup of your own sweat or a cup of your own urine? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have everything you eat be too salty or not salty enough, no matter how much salt you add? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather know when you are going to die or how you are going to die? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather be able to see 10 minutes into your own future or 10 minutes into the future of anyone but yourself? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather find your true love or a suitcase with five million dollars inside? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather drink a glass of milk that's just a bit sour or a glass of water with a hair in it? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather never be able to eat meat or never be able to eat vegetables? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather your shirts be always two sizes too big or one size too small? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have a photographic memory but never be able to forget embarrassing moments or forget everything as soon as it happens? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather accidentally scream the wrong name in bed or have your partner scream the wrong name? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather live without the internet or live without AC and heating? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather never use social media sites/apps again or never watch another movie or TV show? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have unlimited respect or unlimited power? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather the general public think you are a horrible person but your family be very proud of you, or your family think you are a horrible person but the general public be very proud of you? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather lose your left hand or right foot? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather vomit on your hero or have your hero vomit on you? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather always have to say everything on your mind or never speak again? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather be in jail for a year or lose a year off your life? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather get a face tattoo of something you choose or a tattoo in a discreet area but someone else chooses? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather wear the same pair of socks for a month or the same pair of underwear for a week? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather accidentally be responsible for the death of a child or accidentally be responsible for the deaths of three adults? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather go to jail for 4 years for something you didn't do or get away with something horrible you did but always live in fear of being caught? Minority drinks 2. If a draw happens, everybody drinks.",
            "Would you rather have the ability to read minds or the ability to see the future? Minority drinks 2.",
            "Would you rather have no taste buds or be color blind? Minority drinks 2.",
            "Would you rather always be overdressed or always be underdressed? Minority drinks 2.",
            "Would you rather be famous for your talents or infamous for your crimes? Minority drinks 2.",
            "Would you rather live in a world with no problems or a world with no rules? Minority drinks 2.",
            "Would you rather always say everything on your mind or never speak again? Minority drinks 2.",
            "Would you rather be able to control fire or water? Minority drinks 2.",
            "Would you rather have a photographic memory or an IQ of 200? Minority drinks 2.",
            "Would you rather be fluent in all languages or be a master of every musical instrument? Minority drinks 2.",
            "Would you rather never have to sleep or never have to eat? Minority drinks 2.",
        ],
    },
    "Scenario": {
        "cards": [
            "If you could trade lives with anyone in this room for a day, who would it be and why? That person drinks 3 sips.",
            "If you had to be stranded on a deserted island with one people from this group, who would they be? Both of you drinks.",
        ]
    },
    "Scenario for all": {
        "settings": {"for_all_players": True},
        "cards": [
            "If you had to give up either social media or texting, which would you choose? Everyone votes, minority drinks 3 sips.",
            "If you had to give up either your favorite social media platform or your favorite streaming service, which would you choose? Everyone votes, minority drinks 3 sips.",
            "If you could instantly gain any skill, what would it be? The least useful skill (voted by the group) drinks 2 sips.",
            "If you could have any superpower, what would it be? The group votes on the lamest power, and that person drinks 3 sips.",
            "If you had to get a tattoo right now, what would it be and where? The group votes, and the worst idea drinks 4 sips.",
            "If you could switch lives with any celebrity, who would it be? The group votes, and the least popular choice drinks 3 sips.",
            "If you had to lose one of your five senses, which would it be? The group votes, and the minority drinks 2 sips.",
            "If you had to give up either your favorite type of music or your favorite artist/band, which would you choose? Everyone votes, minority drinks 3 sips.",
            "If you had to give up either your favorite snack or your favorite dessert, which would you choose? Everyone votes, minority drinks 3 sips.",
            "If you had to give up either your favorite piece of clothing or your favorite accessory, which would you choose? Everyone votes, minority drinks 3 sips.",
            "If you had to give up either your favorite TV show or your favorite movie, which would you choose? Everyone votes, minority drinks 3 sips.",
            "If you had to give up either chocolate or cheese forever, which would you choose? Everyone votes, minority drinks 3 sips.",
            "If you had to give up either hot showers or air conditioning/heating/fan, which would you choose? Everyone votes, minority drinks 3 sips.",
            "If you had to give up either your smartphone or your computer, which would you choose? Everyone votes, minority drinks 3 sips.",
            "If you had to give up either coffee or alcohol forever, which would you choose? Everyone votes, minority drinks 3 sips.",
            "If you could bring back any extinct animal, which would you choose? The most dangerous choice drinks 3 sips.",
            "If you could be any age for the rest of your life, what age would you choose? The oldest age drinks 2 sips.",
            "If you could go back in time and change one thing, what would it be? The most interesting answer (voted by the group) gives out 4 sips.",
            "If you had to be an animal for a day, what would you be? The group votes on the most boring choice, and that person drinks 3 sips.",
            "If you could instantly learn any language, which would it be? The least useful language (voted by the group) drinks 2 sips.",
            "If you could have any job in the world, regardless of qualifications, what would it be? The least ambitious person drinks 2 sips.",
            "If you could master any musical instrument instantly, which would you choose? The least popular choice drinks 2 sips.",
            "If you had to live in another country for a year, where would you go? The most dangerous choice (voted by the group) drinks 3 sips.",
            "If you had to give up either bathing or brushing your teeth for a month, which would you choose? Everyone votes, minority drinks 3 sips.",
            "If you could have any animal as a pet, regardless of practicality, what would it be? The most dangerous choice drinks 3 sips.",
            "If you had to wear one outfit for the rest of your life, what would it be? The least practical outfit (voted by the group) drinks 2 sips.",
            "If you had to live without either music or movies for the rest of your life, which would you choose? Everyone votes, minority drinks 3 sips.",
            "If you could change one law, what would it be? The most selfish law change (voted by the group) drinks 3 sips.",
            "If you had to lose either your long-term or short-term memory, which would you choose? Everyone votes, minority drinks 3 sips.",
        ],
    },
}
